#!/bin/bash

# Author : Luke Park

# Get the host ip for use in certificate generation
HOST_IP=$(echo $(hostname -I | awk '{print $1}'))
echo -e "\n\033[01;92m Setting up Overwatch for : $HOST_IP\n\033[0;0m"

# Generate the certificates if they cannout be found
if [ ! -f apache/build/certs/overwatch.key ] || [ ! -f apache/build/certs/overwatch.crt ]; then
	echo -e "\033[01;93mNo certificates detected. Generating them now...\033[0;0m"
	openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout apache/build/certs/overwatch.key -out apache/build/certs/overwatch.crt -subj "/C=UK/ST=England/L=Bristol/O=ParkSystems/CN=${HOST_IP}"
	if [ $? -eq 0 ]; then
		echo -e "\033[01;92mCertificates successfully generated."
		./apache/key-formatter
	else
		echo -e "\033[01;101 CERTIFICATE GENERATION FAILED \033[0;0m"
		exit
	fi
else
	echo -e "\033[01;92mCertificates found!\033[0;0m"
fi

# Build the docker containers
if [[ $1 = "build" ]]; then

	docker compose build

	if [ $? -eq 0 ]; then
		echo -e "\n\033[01;102m BUILD COMPLETED \033[0;0m\n"
	else
		echo -e "\n\033[01;91m BUILD FAILED \033[0;0m\n"
		exit
	fi
fi

# Run the docker containers in detached mode
docker compose up apache -d
docker compose up overwatch -d

